### ISSUE TITLE
StimulusStarField plugin is missing

### ISSUE THREAD

**Issue by maxlklaxl** [strawlab/flyvr#10]

**Comment by maxlklaxl** [comment]
Data from this stimulus was in the paper for the fish path following

In my recollection, it was the "non CUDA" version. Branch was "maxFishvr" and I think the branch never got merged to master or moved from the strawlab-freeflight-experiments. I think we just forgot that the early fish experiments were done on a different branch / older version.

**Comment by astraw** [comment]
I will try to find the original sources. Until now, unfortunately I have had higher priorities than your issue. I will get to it as soon as I can. Please keep correspondence regarding this issue here rather than private email.

**Comment by maxlklaxl** [comment]
Thank's for looking into this. I should have a backup of the data and the stimulus somewhere, if this is of any help.

**Comment by astraw** [comment]
Released here https://github.com/strawlab/freemovr-paper-stimuli
